#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=12,mem=32GB
#PBS -m abe
#PBS -M adamo010@umn.edu
module load breseq
breseq -r ./Amp_P10_seqs/EcoliGenome.gb -r ./Amp_P10_seqs/EplasmidF.gb -r ./Amp_P10_seqs/SalmonellaGenome.gb -r ./Amp_P10_seqs/pSLT2.gb -r ./Amp_P10_seqs/pSR27.gb ./Amp_P10_seqs/rMM176_S24_R1_001.fastq ./Amp_P10_seqs/rMM176_S24_R2_001.fastq -p -j 12 -o ./Amp_P10_seqs/rMM176


module load kallisto
kallisto index -i ./home/blekhman/adamo010/Mayo_RNAseq_project/transcripts.idx transcripts.fasta.gz
kallisto quant -i <indexfile> -b 100 -o <outputfile name> <fastqfile with forward reads> <fastqfile with backward reads>
